const basic = [{
        animal: 'cat',
        name: 'Purina Pro Plan',
        imageMain: 'https://avatars.mds.yandex.net/i?id=97884beb83f584cf3ebe9a1de9bd36af-5339089-images-thumbs&n=13',
        imageOther: 'https://avatars.mds.yandex.net/get-mpic/5245452/img_id6969097289587066844.jpeg/orig',
        description: 'Canned full-fledged dietary food for adult cats for dissolving struvite stones and reducing the likelihood of their re-formation, with properties of acidification of urine and low magnesium content. The use of this feed is recommended under the supervision of a veterinarian. Suitable for all breeds.',
        cost: '7,14',
        brand: 'Purina',
        taste: 'Turkey',
        weight: '195',
        TypeOfFeed: 'wet',
    },
    {
        animal: 'cat',
        name: `Hill's Beef-flavored Spiders`,
        imageMain: 'https://zoolan.by/image/cache/catalog/a1-1200x1200.jpeg',
        imageOther: 'https://ravta.ru/upload/iblock/621/621ac2c7b44d45b404d4999cc943e662.jpg',
        description: `Hill's k/d Kidney Care is a special diet for cats with kidney failure or heart disease.`,
        cost: '4,09',
        brand: `Hill's`,
        taste: 'Beef',
        weight: '85',
        TypeOfFeed: 'wet',
    },
    {
        animal: 'cat',
        name: `Kitekat for adult cats with rabbit flavor`,
        imageMain: 'https://zoobazar.by/upload/resize_cache/iblock/24c/46k6ztijee4m95cmqel1f4amlfmgbaj0/520_520_040cd750bba9870f18aada2478b24840a/detail_pictureb7f0ef6e_37e8_4cf9_a4cf_8037308dc82d.jpg',
        imageOther: 'https://zoomag63.ru/upload/iblock/cd5/ir6hw7kicnccvo7zwakmymmlfswvtjm3.jpeg',
        description: `Kitekat Tender Rabbit in Jelly is a portion of juicy pieces with rabbit cooked according to a special recipe. It is based on a balanced nutrition formula that contains proteins, minerals, vitamins, taurine and animal fats. Kitekat is the optimal source of vitality for a cat.`,
        cost: '0,68',
        brand: `Kitekat`,
        taste: 'Rabbit',
        weight: '85',
        TypeOfFeed: 'wet',
    },
    {
        animal: 'cat',
        name: `Pieces in Royal Canin jelly`,
        imageMain: 'https://palladi.ru/upload/iblock/154/154c752c5716f1f534d3462e86758376.jpg',
        imageOther: 'https://zoo-discont.ru/upload/iblock/cea/42u6llpimq61x962vnoslmn2svd3oma0.jpg',
        description: `Adult cats that are constantly kept indoors are less active compared to animals that have access to the street. That's why a full-fledged balanced diet rich in valuable nutrients is so important for their health.`,
        cost: '2,13',
        brand: `Royal Canin`,
        taste: 'Bird',
        weight: '85',
        TypeOfFeed: 'wet',
    },
    // {
    //     animal: 'dog',
    //     name: ``,
    //     imageMain: '',
    //     imageOther: '',
    //     description: ``,
    //     cost: '',
    //     brand: ``,
    //     taste: '',
    //     weight: '',
    //     TypeOfFeed: '',
    // }, 
]

export default basic;
